language: ruby
rvm:
  - "5.1.4"
env:
  - DB=sqlite3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e 'create database mydb_test'
bundler_args: --binstubs=./bundler_stubs